services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    image: projekt_court_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      "ConnectionStrings__DefaultConnection": "Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres;"
    ports:
      - 8080:8080

volumes:
  pgdata: {}